# Setup
title:               mixpix3ls
tagline:             'Musings on tech'
description:         'Some thoughts on tech'
url:                 http://mixpix3ls.net
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Sayam Masood
  url:               https://mixpix3ls.net
  email:             mixpix3ls@protonmail.com

# Gems
plugins:
  - jekyll-paginate

# Build settings
markdown: kramdown